fauxra/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from questions import views

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.index, name='index'),
    url(r'^questions/', include('questions.urls', namespace='questions')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^images/', include('images.urls', namespace='images')),
)

questions/urls.py
from django.conf.urls import patterns, url

from questions import views, feeds

urlpatterns = patterns('',
    # questions
    url(r'^$', views.index, name='index'),
    url(r'^tagged/(?P<tag_slug>[\w-]+)/$', views.tagged, name='tagged'),
    url(r'^new/$', views.new_question, name='new'),
    url(r'^(?P<question_id>\d+)/$', views.show_question, name='show'),
    url(r'^(?P<question_id>\d+)/edit/$', views.edit_question, name='edit'),
    url(r'^(?P<question_id>\d+)/update/$', views.update_question, name='update'),
    url(r'^create/$', views.create_question, name='create'),

    # answers
    url(r'^(?P<question_id>\d+)/answers/new/$', views.new_answer, name='new_answer'),
    url(r'^(?P<question_id>\d+)/answers/create/$', views.create_answer,
        name='create_answer'),
    url(r'^answers/(?P<answer_id>\d+)/edit/$',
        views.edit_answer, name='edit_answer' ),
    url(r'^answers/(?P<answer_id>\d+)/update/$',
        views.update_answer, name='update_answer' ),

    # voting
    url(r'^vote_up/(?P<question_id>\d+)/$', views.vote_up, name='vote_up'),
    url(r'^vote_down/(?P<question_id>\d+)/$', views.vote_down, name='vote_down'),
    url(r'^vote_up_answer/(?P<answer_id>\d+)/$', views.vote_up_answer,
        name='vote_up_answer'),
    url(r'^vote_down_answer/(?P<answer_id>\d+)/$', views.vote_down_answer,
        name='vote_down_answer'),

    # rss
    url(r'^feed/$', feeds.LatestQuestionsFeed(), name="feed"),
    url(r'^(?P<question_id>\d+)/answers/feed/$', feeds.LatestAnswersFeed(),
        name="answers_feed"),
)

questions/models.py
from django.db import models

from django.contrib.auth.models import User

from taggit.managers import TaggableManager

from django.contrib.syndication.views import Feed

import datetime

class Question(models.Model):
    text = models.TextField()
    date = models.DateTimeField('date published')
    date_updated = models.DateTimeField('date updated', null=True)
    user = models.ForeignKey(User)
    votes = models.IntegerField(default=0)
    tags = TaggableManager(blank=True)
    last_activity_date = models.DateTimeField('last activity date', null=True)

    def save(self, *args, **kwargs):
        self.last_activity_date = datetime.datetime.now()
        super(Question, self).save(*args, **kwargs)

    def update_votes(self):
        question_votes = QuestionVote.objects.filter(question=self)
        vote_count = 0

        for vote in question_votes:
            vote_count += vote.value

        self.votes = vote_count

    def __str__(self):
        return self.text

class Answer(models.Model):
    question = models.ForeignKey(Question)
    text = models.TextField()
    date = models.DateTimeField('date published')
    date_updated = models.DateTimeField('date updated', null=True)
    user = models.ForeignKey(User)
    votes = models.IntegerField(default=0)

    def update_votes(self):
        answer_votes = AnswerVote.objects.filter(answer=self)
        vote_count = 0

        for vote in answer_votes:
            vote_count += vote.value

        self.votes = vote_count

    def save(self, *args, **kwargs):
        self.question.last_activity_date = datetime.datetime.now()
        self.question.save()
        super(Answer, self).save(*args, **kwargs)

    def __str__(self):
        text = self.text

        return text

class QuestionVote(models.Model):
    user = models.ForeignKey(User)
    question = models.ForeignKey(Question)
    value = models.IntegerField()

class AnswerVote(models.Model):
    user = models.ForeignKey(User)
    answer = models.ForeignKey(Answer)
    value = models.IntegerField()

class LatestAnswersFeed(Feed):
    link = "/"

    def get_object(self, request, question_id):
        return get_object_or_404(Question, pk=question_id)

    def items(self, question):
        return Answer.objects.filter(question=question).order_by('-date')

    def title(self, item):
        return "Latest answers on Fauxra for the question: %s" % item.question.text

    def item_title(self, item):
        return item.text

    def item_link(self, item):
        return reverse("questions:show", args=[item.question.id])


class LatestQuestionsFeed(Feed):
    title = "Latest questions from Fauxra"
    link = "/"
    description = "See the latest questions posted to Fauxra."

    def items(self):
        return Question.objects.order_by('-date')

    def item_title(self, item):
        return truncatechars(item.text, 500)

    def item_link(self, item):
        return reverse("questions:show", args=[item.id])

questions/forms.py
from django import forms
from django.forms import ModelForm
from questions.models import Question, Answer

class QuestionForm(ModelForm):
    class Meta:
        model = Question
        fields = ['text', 'tags']

class AnswerForm(ModelForm):
    class Meta:
        model = Answer
        fields = ['text']

questions/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import Http404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from questions.models import Question, Answer, QuestionVote, AnswerVote
from questions.forms import QuestionForm, AnswerForm
from django.db.models import Count

from taggit.models import Tag

import datetime

def index(request):
    questions_list = Question.objects.annotate(
        null_last_activity_date=Count('last_activity_date')
    ).order_by('-null_last_activity_date', '-last_activity_date')
    paginator = Paginator(questions_list, 10)

    page = request.GET.get('page')

    try:
        questions = paginator.page(page)
    except PageNotAnInteger:
        questions = paginator.page(1)
    except EmptyPage:
        questions = paginator.page(paginator.num_pages)

    context = { 'questions': questions }
    return render(request, 'questions/index.html', context)

def tagged(request, tag_slug):
    tag = get_object_or_404(Tag, slug=tag_slug)
    questions_list = Question.objects.filter(tags=tag)

    paginator = Paginator(questions_list, 10)

    page = request.GET.get('page')

    try:
        questions = paginator.page(page)
    except PageNotAnInteger:
        questions = paginator.page(1)
    except EmptyPage:
        questions = paginator.page(paginator.num_pages)

    context = { 'questions': questions, 'tag': tag }
    return render(request, 'questions/tagged.html', context)

def show_question(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    answers = question.answer_set.order_by('votes').reverse()
    context = { 'question': question, 'answers': answers }
    question.tags
    return render(request, 'questions/show.html', context)

def new_question(request):
    if request.user.is_authenticated():
        form = QuestionForm()
        context =  { 'form': form }
        return render(request, 'questions/new.html', context)
    else:
        return redirect('accounts:sign_in')

def create_question(request):
    if request.user.is_authenticated():
        form = QuestionForm(request.POST)

        if form.is_valid():
            new_question = form.save(commit=False)
            new_question.date = datetime.datetime.now()
            new_question.user = request.user
            new_question.save()

            tags = form.cleaned_data['tags']
            new_question.tags.clear()
            for tag in tags:
                new_question.tags.add(tag)

            new_question.save()
            return redirect('questions:show', question_id = new_question.id)
        else:
            return redirect('questions:new')
    else:
        return redirect('/')

def update_question(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    if not request.user == question.user:
        return redirect('questions:show', question)

    form = QuestionForm(request.POST)

    if form.is_valid():
        tags = form.cleaned_data['tags']
        question.tags.clear()
        for tag in tags:
            question.tags.add(tag)

        question.date_updated = datetime.datetime.now()
        question.text = form.cleaned_data['text']
        question.save()

        return redirect('questions:show', question_id=question_id)
    else:
        return redirect('questions:edit', question_id=question_id)

def update_answer(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)

    if not request.user == answer.user:
        return redirect('questions:show', answer.question)

    form = AnswerForm(request.POST)

    if form.is_valid():
        answer.date_updated = datetime.datetime.now()
        answer.text = form.cleaned_data['text']
        answer.save()

        return redirect('questions:show', answer.question.id)

    context = { 'form': form }
    return render(request, 'questions:edit_answer', context)

def edit_question(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    if not request.user == question.user:
        return redirect('questions:show', question)

    form = QuestionForm(instance=question)
    context = { 'form': form, 'question': question }
    return render(request, 'questions/edit.html', context)

def edit_answer(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)

    if not request.user == answer.user:
        return redirect('questions:show', answer.question)

    form = AnswerForm(instance=answer)
    context = { 'form': form, 'question': answer.question, 'answer': answer }
    return render(request, 'answers/edit.html', context)

def new_answer(request, question_id):
    if request.user.is_authenticated():
        form = AnswerForm()
        context = { 'form': form , 'question_id': question_id }
        return render(request, 'questions/answers/new.html', context)
    else:
        return redirect('accounts:sign_in')

def create_answer(request, question_id):
    form = AnswerForm(request.POST)
    new_answer = form.save(commit=False)
    new_answer.date = datetime.datetime.now()
    question = get_object_or_404(Question, pk=question_id)
    new_answer.question = question
    new_answer.user = request.user
    new_answer.save()
    return redirect('questions:show', question_id)

def vote_up(request, question_id):
    return vote_foo_question(request, question_id, 1)

def vote_down(request, question_id):
    return vote_foo_question(request, question_id, -1)

def vote_foo_question(request, question_id, value):
    if not request.user.is_authenticated():
        return redirect('questions:show', question_id)

    user_id = request.user.id
    question = get_object_or_404(Question, pk=question_id)
    vote = QuestionVote.objects.filter(user_id=user_id, question=question).first()

    if vote is None:
        vote = QuestionVote()
        vote.user_id = user_id
        vote.question = question

    vote.value = value
    vote.save()
    question.update_votes()
    question.save()

    return redirect('questions:show', question_id)

def vote_up_answer(request, answer_id):
    return vote_foo_answer(request, answer_id, 1)
def vote_down_answer(request, answer_id):
    return vote_foo_answer(request, answer_id, -1)

def vote_foo_answer(request, answer_id, value):
    answer = get_object_or_404(Answer, pk=answer_id)
    question_id = answer.question_id

    if not request.user.is_authenticated():
        return redirect('questions:show', question_id)

    user_id = request.user.id
    vote = AnswerVote.objects.filter(user_id=user_id, answer=answer).first()

    if vote is None:
        vote = AnswerVote()
        vote.user_id = user_id
        vote.answer = answer

    vote.value = value
    vote.save()
    answer.update_votes()
    answer.save()

    return redirect('questions:show', question_id)

questions/templates/questions/edit.html
{% extends "base.html" %}

{% block content %}
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'questions:update' question.id %}" method="POST">
        {% csrf_token %}

        <table>{{ form }}</table>

        <input type="submit" value="Submit" />

    </form>
{% endblock %}

questions/templates/questions/index.html
{% extends "base.html" %}

{% block content %}

<div class="row">
    <div class="col col-sm-8">
        <h1>Latest Questions</h1>
    </div>
    <div class="col col-sm-4">
        <br>
        <a href="{% url 'questions:new' %}" class="btn btn-success">Create question</a>
    </div>
</div>


    {% if questions %}
        <ul>
            {% for question in questions %}
            <li><a href="{% url 'questions:show' question.id %}"> {{ question.text|truncatechars:500 }}</a></li>
            {% endfor %}
        </ul>

        <nav class="pagination">
            Page {{ questions.number }} of {{ questions.paginator.num_pages }}
            <ul class="pager">
                {% if questions.has_previous %}
                    <li><a href="?page={{ questions.previous_page_number }}">previous</a></li>
                {% endif %}


                {% if questions.has_next%}
                    <li><a href="?page={{ questions.next_page_number }}">next</a></li>
                {% endif %}
            </ul>
        </nav>
    {% else %}
        <p>No questions are available. </p>
    {% endif %}

    <br>

    <a href='{% url "questions:feed" %}' class="btn btn-default">
          <span class="glyphicon glyphicon-book" aria-hidden="true"></span>
          Questions RSS Feed
    </a>

{% endblock %}

questions/templates/questions/new.html
{% extends "base.html" %}

{% block content %}
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'questions:create' %}" method="POST">
        {% csrf_token %}

        <table>{{ form }}</table>

        <input type="submit" value="Submit" />

    </form>
{% endblock %}

questions/templates/questions/show.html
{% extends "base.html" %}

{% load filters %}

{% block content %}


    <div class="panel panel-info">
        <div class="panel-heading">
            <span class="vote-links">
                <span class="badge">
                    {{ question.votes }}
                </span>
                <a href="{% url 'questions:vote_up' question.id %}">
                    <button type="button" class="btn btn-xs btn-default">
                        <span class="glyphicon glyphicon-chevron-up">
                        </span>
                    </button>
                </a>
                <a href="{% url 'questions:vote_down' question.id %}">
                    <button type="button" class="btn btn-xs btn-default">
                        <span class="glyphicon glyphicon-chevron-down">
                        </span>
                    </button>
                </a>
            </span>

            ::

            <em>Asked by </em><strong>{{ question.user.username }}</strong>

            <em>on</em>

            {{ question.date }}

            {% if user == question.user %}
                <span class="edit-link pull-right">
                    <a href="{% url 'questions:edit' question.id %}">Edit question</a>
                </span>
            {% endif %}

        </div>

        <div class="panel-body">
            {% autoescape off %}
                <p>
                    {{ question | replace_urls }}
                </p>
            {% endautoescape %}

            <hr>

            <p>
                <span class="tags">
                    {% if question.tags.count > 0 %}
                            Tagged:
                            {% for tag in question.tags.all %}
                                <a href="{% url 'questions:tagged' tag.slug %}" 
                                    class="btn btn-xs btn-primary">
                                    {{ tag }}
                                </a>
                            {% endfor %}
                    {% else %}
                        No tags.
                    {% endif %}
                </span>

                <span class="updated-time pull-right">
                    <em>Edited: {{ question.date_updated }}</em>
                </span>
            </p>
        </div>
    </div>

    <a href="{% url 'questions:new_answer' question.id %}" class="btn btn-success">Add answer</a>

    <a href='{% url "questions:answers_feed" question.id  %}' class="btn btn-default">
          <span class="glyphicon glyphicon-book" aria-hidden="true"></span>
          Answers RSS Feed
    </a>

    <table class="answers">
    {% for answer in answers %}
        <hr>
        {% include 'answers/_answer.html' with answer=answer %}
    {% endfor %}
    </table>
{% endblock %}

questions/templates/questions/tagged.html
{% extends "base.html" %}

{% block content %}

<div class="row">
    <div class="col col-sm-8">
        <h1>Questions tagged "{{ tag }}"</h1>
    </div>
    <div class="col col-sm-4">
        <br>
        <a href="{% url 'questions:new' %}" class="btn btn-success">Create question</a>
    </div>
</div>


    {% if questions %}
        <ul>
            {% for question in questions %}
            <li><a href="{% url 'questions:show' question.id %}"> {{ question.text|truncatechars:500 }}</a></li>
            {% endfor %}
        </ul>

        <nav class="pagination">
            Page {{ questions.number }} of {{ questions.paginator.num_pages }}
            <ul class="pager">
                {% if questions.has_previous %}
                    <li><a href="?page={{ questions.previous_page_number }}">previous</a></li>
                {% endif %}


                {% if questions.has_next%}
                    <li><a href="?page={{ questions.next_page_number }}">next</a></li>
                {% endif %}
            </ul>
        </nav>
    {% else %}
        <p>No questions are available. </p>
    {% endif %}

{% endblock %}