fauxra/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from questions import views

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.index, name='index'),
    url(r'^questions/', include('questions.urls', namespace='questions')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^images/', include('images.urls', namespace='images')),
)

images/urls.py
from django.conf.urls import patterns, url

from images import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^(?P<image_id>\d+)/$', views.show, name='show'),
    url(r'^new/$', views.new, name='new'),
    url(r'^create/$', views.create, name='create'),
)

images/models.py
from django.db import models
from cloudinary.models import CloudinaryField

class Image(models.Model):
    image = CloudinaryField('image')

images/forms.py
from django import forms
from django.forms import ModelForm
from images.models import Image

class ImageForm(ModelForm):
    class Meta:
        model = Image

images/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404, redirect

from images.models import Image
from images.forms import ImageForm

import cloudinary

def index(request):
    images = Image.objects.all()
    context = { 'images': images}
    return render(request, 'images/index.html', context)

def show(request, image_id):
    image = get_object_or_404(Image, pk=image_id)
    context = { 'image': image }
    return render(request, 'images/show.html', context)

def new(request):
    form = ImageForm()
    context =  { 'form': form }
    return render(request, 'images/new.html', context)

def create(request):
    form = ImageForm(request.POST, request.FILES)

    if form.is_valid():
        form.save()
        return redirect('images:index')

    return redirect('images:new')

images/templates/images/index.html
{% extends "base.html" %}
{% load cloudinary %}

{% block content %}

<div class="row">
    <div class="col col-sm-8">
        <h1>Images</h1>
    </div>
    <div class="col col-sm-4">
        <br>
        <a href="{% url 'images:new' %}" class="btn btn-success">Upload image</a>
    </div>
</div>

    {% if images %}
        <ul>
            {% for image in images %}
                <li><a href="{% url 'images:show' image.id %}">{{image.id}}
                {% cloudinary image.image width=100 %} 
                </a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No images are available. </p>
    {% endif %}

    <a href="{% url 'images:new' %}">Create image</a>

{% endblock %}

images/templates/images/new.html
{% extends "base.html" %}
{% load cloudinary %}

{% block content %}
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'images:create' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        <table>{{ form }}</table>

        <input type="submit" value="Submit" />

    </form>
{% endblock %}

images/templates/images/show.html
{% extends "base.html" %}
{% load cloudinary %}

{% block content %}

{% cloudinary image.image width=500 crop="limit" %}

{% endblock %}