accounts/urls.py
from django.conf.urls import patterns, url

from accounts import views

urlpatterns = patterns('',
    url(r'^sign_in/$', views.sign_in, name='sign_in'),
    url(r'^sign_out/$', views.sign_out, name='sign_out'),
    url(r'^register/$', views.register, name='register'),
)

fauxra/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from questions import views

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.index, name='index'),
    url(r'^questions/', include('questions.urls', namespace='questions')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^images/', include('images.urls', namespace='images')),
)

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate, login, logout

def sign_out(request):
    logout(request)
    return redirect('/')

def sign_in(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('/')
    else:
        form = AuthenticationForm()

    context = {'form': form}
    return render(request, 'accounts/sign_in.html', context)

def register(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = request.POST['username']
            password = request.POST['password1']

            new_user = authenticate(username=username, password=password)

            login(request, new_user)
            return redirect("index")
    else:
        form = UserCreationForm()

    context = {'form': form}
    return render(request, 'accounts/register.html', context)

accounts/templates/accounts/register.html
{% extends "base.html" %}

{% block content %}
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="" method="POST">
        {% csrf_token %}

        <table>{{ form }}</table>

        <input type="submit" value="Submit" />

    </form>
{% endblock %}

accounts/templates/accounts/sign_in.html
{% extends "base.html" %}

{% block content %}
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="" method="POST">
        {% csrf_token %}

        <table>{{ form }}</table>

        <input type="submit" value="Submit" />

    </form>

    <a href="{% url 'accounts:register' %}">Register</a>
{% endblock %}